### ISSUE TITLE
关于源官方地址

### ISSUE THREAD

**Issue by chadspring** [ustclug/mirrorhelp#109]
Homebrew Cask 源使用帮助
在重置为官方地址的说明中，给出的说明为
git remote set-url origin https://github.com/Homebrew/homebrew-cask ，
复制使用后出错，是否应为
git remote set-url origin https://github.com/Homebrew/homebrew-cask.git ？
另：HomeBrew Core源使用帮助中可能存在同样问题。
感谢所做的一切提供巨大的便利。

**Comment by laris** [comment]
yes
https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
```
# brew 程序本身，Homebrew/Linuxbrew 相同
git -C "$(brew --repo)" remote set-url origin https://github.com/Homebrew/brew.git

# 以下针对 mac OS 系统上的 Homebrew
git -C "$(brew --repo homebrew/core)" remote set-url origin https://github.com/Homebrew/homebrew-core.git
git -C "$(brew --repo homebrew/cask)" remote set-url origin https://github.com/Homebrew/homebrew-cask.git
git -C "$(brew --repo homebrew/cask-fonts)" remote set-url origin https://github.com/Homebrew/homebrew-cask-fonts.git
git -C "$(brew --repo homebrew/cask-drivers)" remote set-url origin https://github.com/Homebrew/homebrew-cask-drivers.git

# 以下针对 Linux 系统上的 Linuxbrew
git -C "$(brew --repo homebrew/core)" remote set-url origin https://github.com/Homebrew/linuxbrew-core.git

# 更换后测试工作是否正常
brew update
```

**Comment by taoky** [comment]
我本地测试使用 `git remote set-url origin https://github.com/Homebrew/homebrew-cask` 是正常的……不知道默认安装 homebrew cask 和 core 的情况下 origin 的 url 是怎么写的。

**Comment by zhsj** [comment]
` https://github.com/Homebrew/homebrew-cask` 和 `https://github.com/Homebrew/homebrew-cask.git` 对于git来说没有区别。
