### ISSUE TITLE
snullp 大叔开发的 配置生成器 URL形式的使用规则？

### ISSUE THREAD

**Issue by laris** [ustclug/mirrorhelp#120]
如下连接中提到的配置生成器，URL规则是如何定义的？
wget https://mirrors.ustc.edu.cn/repogen/conf/ubuntu-https-16.04
这样并不能成功。

https://github.com/ustclug/mirrorhelp/blob/master/source/ubuntu.rst
http://mirrors.ustc.edu.cn/help/ubuntu.html
https://mirrors.ustc.edu.cn/repogen/

Tips: 可通过 URL 的形式直接下载配置. 例如:

https://mirrors.ustc.edu.cn/repogen/conf/debian-http-6-sid
https://mirrors.ustc.edu.cn/repogen/conf/archlinux-https-4

**Comment by knight42** [comment]
目前的规则是 
`https://mirrors.ustc.edu.cn/repogen/conf/<distro>-<http/https>-<4/6>(-<code name>)`

比方说你提到的 url 应该是 `https://mirrors.ustc.edu.cn/repogen/conf/ubuntu-https-4-xenial`

**Comment by laris** [comment]
多谢，麻烦更新到配置页面
