### ISSUE TITLE
我目前在同步软件源，希望不要进制我的同步。

### ISSUE THREAD

**Issue by vvickey11** [ustclug/mirrorhelp#123]
我想做elf文件分类，需要用到大量白样本，请不要禁止我的同步。

**Comment by hosiet** [comment]
Hi @vvickey11 ,

目前镜像站的正常使用和同步用户很多，对异常流量的封禁是自动化的。我们并不知道你从哪里发起访问，没有你的身份信息（如 IP 地址）的话也没有办法对策略做进一步的调整。

所以如果真的需要大量同步的话，请向 lug@ustc.edu.cn 发送电子邮件介绍你的身份和发起请求的公网 IP 地址，最好可以包括预计大规模访问镜像站所使用的协议方式与时间范围；如果是校内用户的话请使用校内邮箱发送邮件，站点会优先考虑本校用户的需求。
