### ISSUE TITLE
最近从学校的源更新anaconda会出错

### ISSUE THREAD

**Issue by grayloach1** [ustclug/mirrorhelp#125]
有两个包更新不了，换了官方的源（https://repo.anaconda.com/pkgs/free/），才更新成功。不知道是哪里出了问题。

Downloading and Extracting Packages
icc_rt-2019.0.0      | 9.4 MB    |                                                                                                                                               |   0%
conda-4.5.12         | 1.1 MB    |                                                                                                                                               |   0%

CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.ustc.edu.cn/anaconda/pkgs/main/win-64/icc_rt-2019.0.0-h0cc432a_1.tar.bz2>
Elapsed: 00:00.147089

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.ustc.edu.cn/anaconda/pkgs/main/win-64/conda-4.5.12-py37_0.tar.bz2>
Elapsed: 00:00.099316

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by taoky** [comment]
https://servers.ustclug.org/2019/04/close-anaconda-service/

Closed.
