### ISSUE TITLE
使用 Github API 自动更新 contributor.rst 中的名单

### ISSUE THREAD

**Issue by zhsj** [ustclug/mirrorhelp#133]
https://developer.github.com/v3/repos/statistics/ 中有如下 API

`GET /repos/:owner/:repo/stats/contributors`

可以写一个 sphinx 扩展来自动更新贡献者的名单。

**Comment by taoky** [comment]
现在来看的话，可以考虑用 https://contributors-img.web.app/preview 或者类似的服务来创建 contributor 的头像列表。目前 Linux101 的网站上显示贡献者就是用的这个。

当然如果不合适的话我考虑去学一下怎么写 Sphinx plugin（

**Comment by taoky** [comment]
`curl -L api.github.com/repos/ustclug/mirrorhelp/contributors | jq 'map(.login) | sort'`
