### ISSUE TITLE
这个Rust crate源响应的有问题！

### ISSUE THREAD

**Issue by yaephin** [ustclug/mirrorhelp#139]
### 使用官方配置：
> [source.crates-io]
> replace-with = 'ustc'
> [source.ustc]
> registry = "git://mirrors.ustc.edu.cn/crates.io-index"
`$ cargo build`
![Screenshot from 2019-10-02 17-50-42](https://user-images.githubusercontent.com/26021404/66035393-a2497680-e53d-11e9-9b7c-5feb6b391e41.png)
### 使用github源：
> [source.crates-io]
> registry = "https://github.com/rust-lang/crates.io-index"
`$ cargo build`
![Screenshot from 2019-10-02 17-51-02](https://user-images.githubusercontent.com/26021404/66035494-d329ab80-e53d-11e9-9be3-7b964f8efbc8.png)

OS:ubuntu 18.04
Cargo version: 1.38.0-nightly
还是国内源的速度快，github可以下载但速度还是比较慢的，希望官方能修复下这个问题。

**Comment by taoky** [comment]
Do not create duplicate issues (https://github.com/ustclug/discussions/issues/297)
