### ISSUE TITLE
http://mirrors.ustc.edu.cn/   经常访问不了

### ISSUE THREAD

**Issue by ai930** [ustclug/mirrorhelp#149]
http://mirrors.ustc.edu.cn/   经常访问不了

**Comment by taoky** [comment]
今天早上，由于 NFS 服务器宕机，且 mirrors 服务器没有正确配置 NFS 的 timeout，导致所有的 nginx 进程都陷入 uninterruptible sleep 的状态，目前已经修复。

另外，由于目前存储几乎已满，ZFS 的 IO 性能有一定的下降，在负载量大的时候，也可能出现有时「访问不了」的情况。我们正在配置新的镜像站机器，期望可以在暑假之前配置完成。
