### ISSUE TITLE
Stackage源配置方法失效

### ISSUE THREAD

**Issue by huangdade** [ustclug/mirrorhelp#152]
`setup-info`这一行配置方法失败了，显示说无法解析，应当是一个对象。
我修改成了这样就成功了：
```yaml
setup-info-locations:
- http://mirrors.ustc.edu.cn/stackage/stack-setup.yaml
```
另外，`urls`中的`lts-build-plans`和`nightly-build-plans`则是给出了警告，说是无法识别。

**Comment by taoky** [comment]
复现了，从 https://github.com/commercialhaskell/stack/issues/5270 看的话是 stack 的配置文件格式修改了。

我一会根据 https://mirrors.tuna.tsinghua.edu.cn/help/stackage/ 更新一下使用说明。

**Comment by taoky** [comment]
我根据找到的资料更新了文档。现在文档还有别的问题吗？（因为我不写 Haskell）

**Comment by huangdade** [comment]
暂时应该没了。等我有新发现再提issue。
