### ISSUE TITLE
404？

### ISSUE THREAD

**Issue by zygds** [ustclug/mirrorhelp#157]
我想问一下，按照[文档](https://mirrors.ustc.edu.cn/help/blackarch.html?highlight=blackarch)提示
我设置了pacman.conf而且是添加，但是貌似没用，生成了pacman -Sy archlinux-keyring，全部404了

**Comment by taoky** [comment]
emm，如果你用的发行版是 Black Arch 的话……安装的不应该是 `blackarch-keyring` 吗？文档看起来没问题。

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/50038957/88364514-b6ed4880-cdb5-11ea-8f17-4546a68f93e3.png)
是的，可能我搞错了，但是这样设置也不行，下的是虚拟机文件

**Comment by taoky** [comment]
> ![image](https://user-images.githubusercontent.com/50038957/88364514-b6ed4880-cdb5-11ea-8f17-4546a68f93e3.png)
> 是的，可能我搞错了，但是这样设置也不行，下的是虚拟机文件

我下载 BlackArch 试一下，刚刚看了看文件，BlackArch 的 pacman 照理来说应该去访问 `blackarch.db` 作为数据库文件的……

**Comment by zygds** [comment]
下载虚拟机文件，安装有点烦人，用阿里镜像，快！迅雷
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "taoky"; 
Date: 2020年7月24日(星期五) 下午2:06
To: "ustclug/mirrorhelp"; 
Cc: "troy"; "Author"; 
Subject: Re: [ustclug/mirrorhelp] 404？ (#157)

&nbsp;


  

 是的，可能我搞错了，但是这样设置也不行，下的是虚拟机文件
  
我下载 BlackArch 试一下，刚刚看了看文件，BlackArch 的 pacman 照理来说应该去访问 blackarch.db 作为数据库文件的……

**Comment by taoky** [comment]
我怀疑你对 `/etc/pacman.conf` 文件的编辑有问题。Black Arch 仓库的配置是否在 `[blackarch]` 块里面？从你的出错信息来看，你填到了 `[core]` 或者 `[extra]` 块里面。

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/50038957/88365151-b786de80-cdb7-11ea-915d-2a3b1531b7a4.png)
![image](https://user-images.githubusercontent.com/50038957/88365168-c2da0a00-cdb7-11ea-878d-b318c1bc5a36.png)

**Comment by taoky** [comment]
`/etc/pacman.d` 下面的两个镜像列表，`mirrorlist` 是 Arch Linux 的，`blackarch-mirrorlist` 是 BlackArch 自己的工具的镜像。你不应该在 `mirrorlist` 里面放 BlackArch 的镜像。

**Comment by zygds** [comment]
ok ,明白，关键是好慢，网上都是这样做的，关键是帖子又少，X哥也查不到

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/50038957/88365473-b904d680-cdb8-11ea-8015-a9229a564d14.png)

**Comment by taoky** [comment]
文档更新了，加了一句补充的说明，现在应该没有问题了。

**Comment by zygds** [comment]
好的

**Comment by zygds** [comment]
这个留在这吧，或许会帮到别人
