### ISSUE TITLE
文档中 Docker Hub 的地址未实际指向科大源

### ISSUE THREAD

**Issue by NageNalock** [ustclug/mirrorhelp#158]
文档页面: https://mirrors.ustc.edu.cn/help/dockerhub.html#id1

地址: https://docker.mirrors.ustc.edu.cn/

被重定向至: https://hub-mirror.c.163.com/

请问这是否符合预期, 如果是的话希望能在文档里说明

**Comment by iBug** [comment]
由于服务压力及服务资源的考虑，我们的 Docker Hub 源前段时间停止了对科大校外的服务，从校外访问会 302 到网易云的 Docker Hub 镜像。

**Comment by iBug** [comment]
> 由于服务压力及服务资源的考虑，我们的 Docker Hub 源前段时间停止了对科大校外的服务，从校外访问会 302 到网易云的 Docker Hub 镜像。


看起来教育网直连 `registry-1.docker.io` 速度不赖，重开了。

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/help/dockerhub.html

补充了目前 dockerhub, gcr 和 quay 容器镜像缓存的情况，以及手工搭建本地镜像缓存的参考方式。

> 看起来教育网直连 `registry-1.docker.io` 速度不赖，重开了。

然而之后测试的时候发现访问的质量仍然十分糟糕，所以目前仍然采取校外 302 至其他站点的方式。

**Comment by zhsj** [comment]
gcr 302 到阿里云是错的。。阿里云并不提供 gcr 的代理。国内也没有其他 gcr 代理。

**Comment by taoky** [comment]
> gcr 302 到阿里云是错的。。阿里云并不提供 gcr 的代理。国内也没有其他 gcr 代理。

当时测试的时候 registry.cn-hangzhou.aliyuncs.com/google_containers/ 是有东西，也能 pull 镜像下来的……至少对 k8s 的场景来说应该够了。

**Comment by zhsj** [comment]
> > gcr 302 到阿里云是错的。。阿里云并不提供 gcr 的代理。国内也没有其他 gcr 代理。
> 
> 当时测试的时候 registry.cn-hangzhou.aliyuncs.com/google_containers/ 是有东西，也能 pull 镜像下来的……至少对 k8s 的场景来说应该够了。

那个不是反代，是有人定时传上去的。。而且tag比官方少。

**Comment by zhsj** [comment]
而且gcr上也不止google_containers一个项目，感觉在阿里云上创建个其他gcr同名项目就能劫持了 🤔

**Comment by taoky** [comment]
> 而且gcr上也不止google_containers一个项目，感觉在阿里云上创建个其他gcr同名项目就能劫持了 🤔

确实是个问题……那就先改成 403 吧……

**Comment by wswind** [comment]
`minikube  start --help`的帮助说明都是建议使用该地址，应该不存在什么安全隐患
```
      --image-repository='': Alternative image repository to pull docker images from. This can be used when you have
limited access to gcr.io. Set it to "auto" to let minikube decide one for you. For Chinese mainland users, you may use
local gcr.io mirrors such as registry.cn-hangzhou.aliyuncs.com/google_containers
```
我理解你自己上传的镜像应该是传到你自己的命名空间下的，如：
`registry.cn-chengdu.aliyuncs.com/<namespace>/<imagename>  `
**google_containers**命名空间，是阿里云专门用来放谷歌镜像的，你自己是传不进去的

**Comment by zhsj** [comment]
> 我理解你自己上传的镜像应该是传到你自己的命名空间下的，如：
> `registry.cn-chengdu.aliyuncs.com/<namespace>/<imagename> `
> **google_containers**命名空间，是阿里云专门用来放谷歌镜像的，你自己是传不进去的

前面说的是，如果 gcr.mirrors.ustc.edu.cn/google_containers 302 到 registry.cn-hangzhou.aliyuncs.com/google_containers 是没有问题的。但不能把 gcr.mirrors.ustc.edu.cn 下所有的内容都 302 到 registry.cn-hangzhou.aliyuncs.com。

**Comment by zhsj** [comment]
注意 gcr.io 和 k8s.gcr.io 是不一样的。k8s.gcr.io 只是 gcr.io 里的一个项目（namespace）。

**Comment by wswind** [comment]
了解了,谢谢

**Comment by wxmeng04** [comment]
啥时候我们也搞个国内自己的镜像站？现在都没地方搞镜像了，基本上稍微有能力的企业都要自建仓库，从基础镜像搞起了。

**Comment by jingjingxyk** [comment]
> 啥时候我们也搞个国内自己的镜像站？现在都没地方搞镜像了，基本上稍微有能力的企业都要自建仓库，从基础镜像搞起了。

凑合用 https://hub.atomgit.com/
