### ISSUE TITLE
`Homebrew Bottles 源使用帮助` 疑问

### ISSUE THREAD

**Issue by laris** [ustclug/mirrorhelp#163]
1. **homebrew/homebrew-core**写法是否错误？homebrew-core不应该在homebrew-bottles里的。
From: http://mirrors.ustc.edu.cn/help/homebrew-bottles.html
homebrew-core是否应该是这个？ http://mirrors.ustc.edu.cn/help/homebrew-core.git.html

2. **收录仓库** 更新
另外，这个https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/ 文件太多打不开，不确定收录仓库是否准确，可否更新**收录仓库**列表或者打开https预览？

```
收录仓库
homebrew/homebrew-core
homebrew/homebrew-dupes
homebrew/homebrew-php
homebrew/homebrew-science
homebrew/homebrew-nginx
homebrew/homebrew-apache
homebrew/homebrew-portable
```

**Comment by taoky** [comment]
1. homebrew-bottles 是预编译的二进制包，homebrew-core 是 default 的 formulae（包定义），两者并不冲突。
2. homebrew-bottles 的收录仓库列表确实可能不准确，之后会更新。

**Comment by taoky** [comment]
> 2. homebrew-bottles 的收录仓库列表确实可能不准确，之后会更新。

我看了 <https://bintray.com/homebrew/bottles>，如果我没理解错的话应该是只有 Homebrew/homebrew-core 的。

**Comment by taoky** [comment]
fb31acf

如果有同步其他 tap 的 bottles 的需要，欢迎到 https://github.com/ustclug/mirrorrequest/issues 反馈。

**Comment by laris** [comment]
Thanks
