### ISSUE TITLE
HOMEBREW_BREW_GIT_REMOTE 不能解决 brew 首次安装慢的问题

### ISSUE THREAD

**Issue by hezhib** [ustclug/mirrorhelp#164]
hello，我这边通过设置 HOMEBREW_BREW_GIT_REMOTE 变量，首次安装时，并不能从 https://mirrors.ustc.edu.cn/brew.git 镜像地址 clone。我看执行过程的提示，依然是从 https://github.com/Homebrew/brew 地址 clone。HOMEBREW_BREW_GIT_REMOTE 只是在下载完毕后，执行 brew.sh 的时候生效，并将远程仓库地址修改为 https://mirrors.ustc.edu.cn/brew.git（后面使用 brew update 可以正常使用 ustc 的源）。所以个人认为使用 HOMEBREW_BREW_GIT_REMOTE 并不能解决首次安装慢的问题。

下面是我安装的代码。
HOMEBREW_BREW_GIT_REMOTE=https://mirrors.ustc.edu.cn/brew.git HOMEBREW_CORE_GIT_REMOTE=https://mirrors.ustc.edu.cn/homebrew-core.git bash install.sh

本人还是小白一枚，如有不对还请多多指正。

**Comment by hezhib** [comment]
> hello，我这边通过设置 HOMEBREW_BREW_GIT_REMOTE 变量，首次安装时，并不能从 https://mirrors.ustc.edu.cn/brew.git 镜像地址 clone。我看执行过程的提示，依然是从 https://github.com/Homebrew/brew 地址 clone。HOMEBREW_BREW_GIT_REMOTE 只是在下载完毕后，执行 brew.sh 的时候生效，并将远程仓库地址修改为 [https://mirrors.ustc.edu.cn/brew.git（后面使用](https://mirrors.ustc.edu.cn/brew.git%EF%BC%88%E5%90%8E%E9%9D%A2%E4%BD%BF%E7%94%A8) brew update 可以正常使用 ustc 的源）。所以个人认为使用 HOMEBREW_BREW_GIT_REMOTE 并不能解决首次安装慢的问题。
> 
> 下面是我安装的代码。
> HOMEBREW_BREW_GIT_REMOTE=https://mirrors.ustc.edu.cn/brew.git HOMEBREW_CORE_GIT_REMOTE=https://mirrors.ustc.edu.cn/homebrew-core.git bash install.sh
> 
> 本人还是小白一枚，如有不对还请多多指正。

[https://github.com/ustclug/mirrorhelp/blob/master/source/brew.git.rst](url)

**Comment by taoky** [comment]
确实不能，还是只能修改 install.sh 中的 `BREW_REPO` 变量，因为脚本里直接把 brew.sh 仓库的 `remote.origin.url` 设置成了 `BREW_REPO`，然后就 `git fetch origin` 了。当时读脚本的时候在这里理解有点问题……
