### ISSUE TITLE
Fedora 帮助文档两处问题

### ISSUE THREAD

**Issue by coiby** [ustclug/mirrorhelp#166]
1. Fedora 33中的baseurl 是 `http://download.example/pub/fedora/linux`是这样的形式，比如 `/etc/yum.repos.d/fedora-updates.repo`的内容
```
[updates]
name=Fedora $releasever - $basearch - Updates
#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/$basearch/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
```
所以目前sed的匹配模式不符合
```sh
sudo sed -e 's|^metalink=|#metalink=|g' \
         -e 's|^#baseurl=http://download.fedoraproject.org/pub/fedora/linux|baseurl=https://mirrors.ustc.edu.cn/fedora|g' \
         -i.bak \
         /etc/yum.repos.d/fedora.repo \
         /etc/yum.repos.d/fedora-modular.repo \
         /etc/yum.repos.d/fedora-updates.repo \
         /etc/yum.repos.d/fedora-updates-modular.repo
```
2. USTC LUG的Fedora源没有updates-modular-source，即`https://mirrors.ustc.edu.cn/fedora/updates/$releasever/Modular/SRPMS/`无效

**Comment by taoky** [comment]
1. `sed` 不符合的问题已在 9ba0eb101633675341c18e845afc47755094887b 中修复。
2. 之前没有 `updates-modular-source` 的原因是磁盘空间不足，并且 fedora 同步程序的问题导致 Fedora 仓库无法自动删除旧文件，所以当时删掉了 SRPMS 和 development 版本（见 https://github.com/ustclug/discussions/issues/227 和 https://github.com/ustclug/discussions/issues/292 ）。目前因为考虑到 SRPMS 占用的空间事实上不大（Fedora 32 的 SRPMS 大约 50G），所以昨天恢复了 SRPMS 的同步。
