### ISSUE TITLE
希望增加centos 9 stream 的帮助

### ISSUE THREAD

**Issue by maybe-404** [ustclug/mirrorhelp#201]
希望增加centos 9 stream 的帮助

**Comment by taoky** [comment]
CentOS 9 Stream 更换镜像站的方式和 [8 Stream 的帮助](https://mirrors.ustc.edu.cn/help/centos.html)应该是几乎一致的。如果需要的话欢迎提交 PR。

**Comment by maybe-404** [comment]
ok
