### ISSUE TITLE
关于Windows安装GHCup的一些坑

### ISSUE THREAD

**Issue by StephenChips** [ustclug/mirrorhelp#210]
1. 首先安装前务必关闭杀毒软件，不然杀毒软件会拦截掉SSH自签证书，导致安装失败。另外防火墙最好也暂时关掉；
2. 最好在家目录`C:\Users\<用户名>`添加文件`_curlrc`，并填入文本`ssl-no-revoke`，否则会报"吊销功能无法检查证书是否吊销"的错误。

**Comment by taoky** [comment]
请问您正在安装什么？

**Comment by StephenChips** [comment]
GHCUP，按照[https://mirrors.ustc.edu.cn/help/ghcup.html](https://mirrors.ustc.edu.cn/help/ghcup.html)的指引；

抱歉我没说清楚。

**Comment by taoky** [comment]
验证 SSL 证书的合法性是保障安全的一部分，帮助不会做出你所述的修改。如果你的环境 SSL 证书必须自签（例如某些公司网络），那么请联系自签证书的人来做相关的技术支持。
