### ISSUE TITLE
GHCup帮助文档源撰写错误

### ISSUE THREAD

**Issue by KingRayCao** [ustclug/mirrorhelp#211]
[http://mirrors.ustc.edu.cn/help/ghcup.html](GHCup的帮助文档)
第二步撰写错误，ghcup-0.0.6.yaml已更新为ghcup-0.0.7.yaml
应为：
url-source:
    OwnSource: https://mirrors.ustc.edu.cn/ghcup/ghcup-metadata/ghcup-0.0.7.yaml

**Comment by taoky** [comment]
添加了一条关于版本的说明，感觉每次 ghcup 滚版本的时候都去更新一个文档也不太现实（而且我不写 haskell，不确定原来的步骤是否能完全对应上新的版本）

**Comment by ksqsf** [comment]
我还是把这个更新了，因为这个只是更新 metadata 的版本，可以预期比较低频，预计不会比半年一次更频繁。

之前加 ghcup 的时候没找到一劳永逸的办法，也许得和上游协商一下。
