### ISSUE TITLE
https://docker.mirrors.ustc.edu.cn/  forbidden啦，怎么办

### ISSUE THREAD

**Issue by jt0129** [ustclug/mirrorhelp#214]

**Comment by zhsj** [comment]
https://mirrors.ustc.edu.cn/help/dockerhub.html

![image](https://user-images.githubusercontent.com/227180/200506019-7615095a-57f4-41ac-b2bc-19bc7958c6c5.png)

**Comment by jt0129** [comment]
谢谢！
