### ISSUE TITLE
Debian源使用帮助需要更新

### ISSUE THREAD

**Issue by cdluminate** [ustclug/mirrorhelp#223]
Debian上游新增了一个 `non-free-firmware` Section.
Debian Sid用户以后就不能保持 `main contrib non-free` 万年不变了。
详情请见：https://github.com/tuna/issues/issues/1658

**Comment by taoky** [comment]
配置生成器已在 https://git.lug.ustc.edu.cn/mirrors/repogen/-/commit/346cc60a79b46cfd963a66aaa2e708f3720398a0 更新。

**Comment by taoky** [comment]
帮助文本已在 https://github.com/ustclug/mirrorhelp/commit/f3182bebe624343db0cb74a3e2fcba19d00e977a 更新。等 bookworm 正式发布的时候应该还要再改一次，所以 issue 先不 close 吧。

**Comment by taoky** [comment]
@cdluminate 此外有些地方需要确认：

- debian-security 是否也加入了 non-free-firmware？
- non-free-firmware 目前是否只应用于 Debian Bookworm/Sid？我注意到似乎诸如 `bullseye-updates` 等 stable 和 oldstable 的发行版本仓库也有 non-free-firmware。

**Comment by cdluminate** [comment]
> @cdluminate 此外有些地方需要确认：
> 
> * debian-security 是否也加入了 non-free-firmware？

实际看起来没有：
http://security.debian.org/debian-security/pool/

> * non-free-firmware 目前是否只应用于 Debian Bookworm/Sid？我注意到似乎诸如 `bullseye-updates` 等 stable 和 oldstable 的发行版本仓库也有 non-free-firmware。

stable/oldstable没有任何理由把包搬到 non-free-firmware，我猜这个新增只是为了mirror的管理以及代码比较统一。
我自己在stable上试了一下，non-free-firmware 没收录软件包。
