### ISSUE TITLE
AOSP tar包checksum不一致

### ISSUE THREAD

**Issue by Yuna95** [ustclug/mirrorhelp#224]
一、问题：
使用curl命令下载的AOSP tar包，本地计算出来的md5和网站上提供的aosp-latest.tar.md5文件中的值不一致。

二、操作步骤：
2.1. 使用如下命令下载AOSP tar包和md5 checksum文件：
curl -OC - https://mirrors.ustc.edu.cn/aosp-monthly/aosp-latest.tar
curl -OC - https://mirrors.ustc.edu.cn/aosp-monthly/aosp-latest.tar.md5

2.2. 下载完成之后，在本地使用如下命令计算AOSP tar包的md5：
md5sum aosp-latest.tar

2.3. 结果
第2步中计算出来的md5值和aosp-latest.tar.md5文件中提供的md5值不一致。

三、备注：
3.1. aosp-latest.tar文件下载过多次，都是这个现象；
3.2. 执行repo sync 2>&1 | tee [sync_remote.log](https://github.com/ustclug/discussions/files/10890846/sync_remote.log)命令的log如附件sync_remote.log所示；
3.3. 执行repo sync -l 2>&1 | tee [sync_local.log](https://github.com/ustclug/discussions/files/10890853/sync_local.log)命令的log如附件sync_local.log所示；

**Comment by Yuna95** [comment]
为什么直接关闭，没有任何说明？

**Comment by Yuna95** [comment]
为什么直接关闭，没有任何说明？

**Comment by iBug** [comment]
1. 与 ustclug/discussions#416 重复了，请不要在多个地方反复发送相同内容，这对于解决问题没有帮助
2. 本仓库是镜像站的帮助页面，不在这里反馈镜像问题

**Comment by Yuna95** [comment]
好的，了解了！

不好意思，给你添麻烦了！一开始没弄懂2个仓库的关系。
