### ISSUE TITLE
turnkeylinux的镜像站能否提供help

### ISSUE THREAD

**Issue by gbm777** [ustclug/mirrorhelp#248]
turnkeylinux的镜像站能否提供help

**Comment by taoky** [comment]
我并不熟识 TurnKey Linux 的用户，如果可以的话能否提交一个 PR？

**Comment by gbm777** [comment]
https://mirrors.ustc.edu.cn/turnkeylinux/ 

关于这个站的使用说明能出一个吗？

**Comment by iBug** [comment]
您好，明确一下，我们没有认识的 TurnKey Linux 用户，因此我们无法编写帮助。如果您可以编写此帮助，请提交一个 PR，谢谢。

**Comment by gbm777** [comment]
我也没找到该怎么使用，特别是PVE中，该修改哪个文件。

**Comment by iBug** [comment]
PVE 镜像的使用请参考 [Proxmox](https://mirrors.ustc.edu.cn/help/proxmox.html#ct-templates) 页面中的 CT Templates 一节。

**Comment by gbm777** [comment]
之前按这个试了，但实际还是从官方镜像下载。

**Comment by iBug** [comment]
那就手动下载放到 `/var/lib/vz/template/cache` 目录下吧

**Comment by gbm777** [comment]
好吧

**Comment by wy414012** [comment]
@gbm777 要想在PVE下使用镜像站，下载turnkeylinux的LXC容器，需要镜像站将turnkeylinux/metadata/pve/aplinfo.dat 中的Location: 选项中的绝对URL路径变更为相对路径后，才能使用，目前无法使用镜像站作为源
![image](https://github.com/ustclug/mirrorhelp/assets/36281137/c2d64642-28f4-4e84-8453-64e1034ac466)
，给官方源发送了反馈，但是这个Linux的官方团队视乎并没有改变的想法. 建议可以直接下架该源！@iBug
