### ISSUE TITLE
qtproject doc: ambiguous sentence?

### ISSUE THREAD

**Issue by ustcljh** [ustclug/mirrorhelp#256]
`qtproject` doc:
``已经不再被官方维护的版本未同步。'' : What's that?

**Comment by taoky** [comment]
https://endoflife.date/qt

**Comment by ustcljh** [comment]
so is it:
_(Versions that are no longer maintained by Qt officially) aren't sync'ed._
or
_Not sync'ing with the versions that are no longer maintained by Qt officially._
