### ISSUE TITLE
考虑去掉标题中的“源使用帮助”

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/mirrorhelp#26]
原因：

* 观感比较凌乱
* help页面收录的显然是镜像使用帮助。没必要重复写出。

![screen shot 2017-01-06 at 1 12 23 am](https://cloud.githubusercontent.com/assets/5450996/21689964/50473f06-d3ad-11e6-9861-e29b80cbd301.png)
![screen shot 2017-01-06 at 1 12 30 am](https://cloud.githubusercontent.com/assets/5450996/21689967/518b7cd8-d3ad-11e6-9862-7f007f8e5129.png)

**Comment by wck963** [comment]
但是这对搜索引擎是不是有好处？

**Comment by gaoyifan** [comment]
有道理！去掉后的确会影响搜索引擎检索。
但借助搜索引擎搜索“xxx源使用帮助”的意义似乎不大......

**Comment by taoky** [comment]
迁移到 mkdocs 之后，由于列表里面的「使用帮助」确实对查阅影响比较大，已经删除。
