### ISSUE TITLE
ubuntu 镜像挂了，拉不下来 

### ISSUE THREAD

**Issue by icetech233** [ustclug/mirrorhelp#262]
Ign:32 https://mirrors.ustc.edu.cn/ubuntu bionic-backports/universe arm64 Packages
Ign:28 https://mirrors.ustc.edu.cn/ubuntu bionic-updates/multiverse arm64 Packages
Err:31 https://mirrors.ustc.edu.cn/ubuntu bionic-backports/main arm64 Packages
  404  Not Found [IP: 202.141.176.110 443]
Ign:32 https://mirrors.ustc.edu.cn/ubuntu bionic-backports/universe arm64 Packages
Fetched 242 kB in 6s (37.7 kB/s)
Reading package lists... Done
E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/bionic/main/binary-arm64/Packages  404  Not Found [IP: 202.141.176.110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/bionic-security/main/binary-arm64/Packages  404  Not Found [IP: 202.141.176.110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/bionic-updates/main/binary-arm64/Packages  404  Not Found [IP: 202.141.176.110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/bionic-backports/main/binary-arm64/Packages  404  Not Found [IP: 202.141.176.110 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by taoky** [comment]
非 x86_64/i386 架构应当使用 ubuntu-ports，这一点在帮助文档中是明确说明了的。
