### ISSUE TITLE
ghcup metadata not up to date

### ISSUE THREAD

**Issue by Erchiusx** [ustclug/mirrorhelp#266]
在ghcup的帮助中：
- 使用的是`ghcup-0.0.7.yaml`
- 然而安装后的ghcup会尝试下载`ghcup-0.0.8.yaml`，且不从镜像站走，而直接走github

手动执行了
```bash
curl https://mirrors.ustc.edu.cn/ghcup/ghcup-metadata/ghcup-0.0.8.yaml > ~/.ghcup/cache/ghcup-0.0.8.yaml
```
后问题暂时消失；
不知道是否应该将安装命令行中改为`ghcup-0.0.8.yaml`

**Comment by taoky** [comment]
有兴趣的话可以交个 PR？因为我们肯定没有精力时刻跟着 ghcup 的最新版本来更新帮助。

**Comment by Erchiusx** [comment]
> 有兴趣的话可以交个 PR？因为我们肯定没有精力时刻跟着 ghcup 的最新版本来更新帮助。

好的
