### ISSUE TITLE
考虑关闭travis-ci对PR的触发

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/mirrorhelp#31]
由于环境变量中包含同步密码，如果将`.travis.yml`改为类似：

```yml
script:
    - echo $RSYNC_PASSWORD
```

则会直接将同步密码打印在日志中，存在较大的安全隐患。

@zhsj 是否考虑关掉对PR的触发？

**Comment by zhsj** [comment]
https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings

    Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

**Comment by zhsj** [comment]
不过需要检测变量是否存在，否则rsync会卡住等密码输入

**Comment by zhsj** [comment]
好吧，部署会略过pr。 。
