### ISSUE TITLE
Debian Multimedia镜像使用帮助页面“手动更新 deb-multimedia-keyring”需更新

### ISSUE THREAD

**Issue by JackieMium** [ustclug/mirrorhelp#34]
[Debian Multimedia镜像使用帮助](https://lug.ustc.edu.cn/wiki/mirrors/help/debian-multimedia)的

> 06/02/2015 :
Maybe I went too quickly to my new GPG key.
If apt-get don't find the new key, do that :
wget https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2015.6.1_all.deb
sudo dpkg -i deb-multimedia-keyring_2015.6.1_all.deb
apt-get update
apt-get should be happy now.

这一部分，现在Multimedia官网deb-multimedia-keyring已经更新了，需要改为`deb-multimedia-keyring_2016.8.1_all.deb`。

**Comment by zhsj** [comment]
这一段主要文字是针对 2015 年 6 月份 deb-multimedia 维护者错误更新 GPG key 而导致的事故。并不是指导用户如何安装 keyring。
