### ISSUE TITLE
npm报错

### ISSUE THREAD

**Issue by regoo** [ustclug/mirrorhelp#5]
#npm --registry http://npm.mirrors.ustc.edu.cn/registry install express

npm http GET http://npm.mirrors.ustc.edu.cn/registry/express
npm http 502 http://npm.mirrors.ustc.edu.cn/registry/express
npm ERR! registry error parsing json
npm http GET http://npm.mirrors.ustc.edu.cn/registry/express
npm http 502 http://npm.mirrors.ustc.edu.cn/registry/express
npm ERR! registry error parsing json

**Comment by hosiet** [comment]
镜像站暂时不会提供 npm 镜像，现已删除位于首页的链接。
