### ISSUE TITLE
dockerhub 源不能用？

### ISSUE THREAD

**Issue by drcege** [ustclug/mirrorhelp#51]
dockerhub 的源到底是哪一个：
`https://docker.mirrors.ustc.edu.cn/` 还是 ` https://mirrors.ustc.edu.cn/dockerhub/`

最近这两个似乎都不能用了？

**Comment by zhsj** [comment]
https://github.com/ustclug/discussions/issues/131

**Comment by knight42** [comment]
新版本的 Docker (moby) 应该只能用 `https://docker.mirrors.ustc.edu.cn/`。如果使用过程中还遇到问题的话，欢迎再次反馈。
