### ISSUE TITLE
source/rust-static.rst  rustup toolchain下载地址需要更新

### ISSUE THREAD

**Issue by notly** [ustclug/mirrorhelp#52]
以及 RUSTUP_UPDATE_ROOT （用于更新 rustup）：

export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup

should be:

以及 RUSTUP_UPDATE_ROOT （用于更新 rustup）：

export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup/dist

the offical is: RUSTUP_UPDATE_ROOT="https://static.rust-lang.org/rustup/dist"

**Comment by knight42** [comment]
唔。。[官方文档](https://github.com/rust-lang-nursery/rustup.rs#environment-variables) 的说法是：
> RUSTUP_UPDATE_ROOT (default https://static.rust-lang.org/rustup) 

另外如果 `export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup/dist` 的话，貌似会出问题：

```
>>> rustup --version                                                                                                 
rustup 1.3.0 (124170c 2017-05-09)
>>> export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup/dist                                     
>>> rustup update                                                                                                    
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates
error: could not download file from 'https://mirrors.ustc.edu.cn/rust-static/rustup/dist/release-stable.toml' to '/tmp/rustup-update.2i01U9ghVyYx/release-stable.toml'
info: caused by: http request returned an unsuccessful status code: 404
```
