### ISSUE TITLE
使用Debian Multimedia源需要导入deb-multimedia-keyring

### ISSUE THREAD

**Issue by whonchen** [ustclug/mirrorhelp#54]
使用Debian Multimedia源需要导入deb-multimedia-keyring 才能使用，建议在 Debian Multimedia 使用帮助中增加导入deb-multimedia-keyring的说明。

**Comment by gaoyifan** [comment]
希望有Multimedia用户能够贡献相关文档

**Comment by zhsj** [comment]
closed in https://github.com/ustclug/mirrorhelp/pull/55
