### ISSUE TITLE
FreeBSD 相关帮助内容待更新

### ISSUE THREAD

**Issue by hosiet** [ustclug/mirrorhelp#75]
当前主页上 freebsd 的帮助链接仍指向 lug.ustc.edu.cn，需要更新并进行替换。

**Comment by gaoyifan** [comment]
@hosiet  其实有17个镜像的帮助链接仍然指向lug.ustc.edu.cn，需要更新并进行替换。

* aosp
* archive.raspberrypi.org
* archlinuxarm
* CPAN
* CRAN
* ctex
* dotdeb
* eclipse
* freebsd
* kde
* linux.git
* msys2
* qtproject
* raspbian
* ros
* scientificlinux
* xbmc

**Comment by gaoyifan** [comment]
个人倾向于交给社区维护。 很多仓库我们自己也用不到。。。。

**Comment by zhsj** [comment]
@gaoyifan 好不容易抓到一个用 freebsd 的用户，freebsd 的帮助文档就靠你了。

**Comment by gaoyifan** [comment]
@zhsj  待我理一理吧...  本周刚开始用FreeBSD，目前有些混乱....

**Comment by gaoyifan** [comment]
link  #78  #81

**Comment by gaoyifan** [comment]
done
