### ISSUE TITLE
raspbian 的两个镜像该由 jessie 改为 stretch 了

### ISSUE THREAD

**Issue by yangxuan8282** [ustclug/mirrorhelp#76]
https://lug.ustc.edu.cn/wiki/mirrors/help/raspbian 这个页面的帮助应该改成：

```
deb http://mirrors.ustc.edu.cn/raspbian/raspbian/ stretch main non-free contrib
deb-src http://mirrors.ustc.edu.cn/raspbian/raspbian/ stretch main non-free contrib
```

https://lug.ustc.edu.cn/wiki/mirrors/help/archive.raspberrypi.org 这个页面的帮助应该改成：

```
deb https://mirrors.ustc.edu.cn/archive.raspberrypi.org/ stretch main ui
```

**Comment by hosiet** [comment]
我们正在从 lug.ustc.edu.cn 上的帮助文档迁移到 mirrors.ustc.edu.cn/help/ 位置的帮助文档。如有时间的话，请为本仓库提供更新的内容并提交 Pull Request，以完成 raspbian 文档的迁移。

**Comment by yangxuan8282** [comment]
@hosiet 是 fork 一份这个 repos，然后把原来两个页面的内容建立两个文件，改成 stretch 就行了吗？

**Comment by hosiet** [comment]
对的，和其它 GitHub 仓库的贡献方式是一样的。

**Comment by yangxuan8282** [comment]
@hosiet 大概改了一下，还没发起 pull requests，在 master 分钟加了两个文件：raspbian.rst 和 raspi_list.rst

按照其他帮助文件改的，好像还得把这两个文件加入 index.rst 里？raspbian 该加到发行版镜像里，raspi_list 该加到发行版镜像还是软件镜像有点拿不定
