### ISSUE TITLE
现有的FreeBSD 镜像说明如何处理？

### ISSUE THREAD

**Issue by ykla** [ustclug/mirrorhelp#82]
见https://lug.ustc.edu.cn/wiki/mirrors/help/freebsd

**Comment by gaoyifan** [comment]
这个仓库里只剩下 release 和 doc 目录了。 类似于 ubuntu-cdimage 与 ubuntu-cloud-image 的功能。

个人意见是帮助文档中描述一下freebsd仓库包含的内容，不需要实质性的换源步骤了。

@hosiet  @zhsj  你们怎么看呢？

**Comment by hosiet** [comment]
我觉得没问题，至少应当把过时内容删除。

**Comment by gaoyifan** [comment]
@hosiet  https://lug.ustc.edu.cn/wiki/mirrors/help/freebsd 似乎这里全部都是过期内容

**Comment by gaoyifan** [comment]
close via #83
