### ISSUE TITLE
建议修改 Anaconda 镜像使用帮助

### ISSUE THREAD

**Issue by ustcjerry** [ustclug/mirrorhelp#94]
看到库中已经包含以下源：

```
Miniconda 
Conda Forge
msys2
bioconda
menpo
```

参考隔壁的：
https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/
应当添加相应的说明

**Comment by hosiet** [comment]
当然。如果你有兴趣的话，欢迎参与编写使用指南并向本项目使用 Pull Request 贡献内容。

**Comment by ustcjerry** [comment]
@hosiet done!
